version: '3.8'

services:
  discovery-service:
    image: discovery-service
    container_name: discovery-service
    build:
      context: ./discovery-service
    ports:
      - "8761:8761"
    networks:
      - bank-network

  gateway-service:
    image: gateway-service
    container_name: gateway-service
    build:
      context: ./gateway-service
    ports:
      - "8888:8888"
    environment:
      - DISCOVERY_SERVER=http://discovery-service:8761/eureka/
      - ALLOWED_ORIGINS=http://localhost:4200
    depends_on:
      - discovery-service
    networks:
      - bank-network

  customer-service:
    image: customer-service
    container_name: customer-service
    build:
      context: ./customer-service
    ports:
      - "8881:8881"
    environment:
      - DISCOVERY_SERVER=http://discovery-service:8761/eureka/
      - MYSQL_USER=root
      - MYSQL_PWD=rootroot
      - MYSQL_HOST=172.18.0.2
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=customer_db
    depends_on:
      - discovery-service
      - gateway-service
    networks:
      - bank-network

  account-service:
    image: account-service
    container_name: account-service
    build:
      context: ./account-service
    ports:
      - "8880:8880"
    environment:
      - DISCOVERY_SERVER=http://discovery-service:8761/eureka/
      - MYSQL_USER=root
      - MYSQL_PWD=rootroot
      - MYSQL_HOST=172.18.0.2
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=account_db
      - AXON_HOST=172.18.0.3
      - AXON_PORT=8124
    depends_on:
      - discovery-service
      - gateway-service
      - customer-service
    networks:
      - bank-network

networks:
  bank-network:
    external: true
