apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: mounanga/gateway-service
          ports:
            - containerPort: 8888
          env:
            - name: DISCOVERY_SERVER
              value: "http://discovery-service:8761/eureka/"
            - name: ALLOWED_ORIGINS
              value: "http://localhost:4200"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: 8888
  selector:
    app: gateway-service